### ISSUE TITLE
Hadoop -ElasticSearch Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask 

### ISSUE THREAD

**Issue by justinjoseph89** [hortonworks/hadoop-tutorials#41]
I was working with 
https://github.com/hortonworks/hadoop-tutorials/blob/master/Community/T07_Elasticsearch_Hadoop_Integration.md  

From this whenever am trying to do
 INSERT OVERWRITE TABLE eslogs SELECT s.time, s.ext, s.ip, s.req, s.res, s.agent FROM logs s;
It gives me an error.

Query ID = root_20150115064545_a1e25c83-335f-4ad7-aae6-52715c4c7e43
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1421294812769_0008, Tracking URL = http://sandbox.hortonworks.com:8088/proxy/application_1421294812769_0008/
Kill Command = /usr/hdp/2.2.0.0-2041/hadoop/bin/hadoop job  -kill job_1421294812769_0008
Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
2015-01-15 06:45:14,712 Stage-0 map = 0%,  reduce = 0%
Ended Job = job_1421294812769_0008 with errors
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched:
Stage-Stage-0:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec

How can i get rid of this error

**Comment by justinjoseph89** [comment]
Changed the jar file into  elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar;

**Comment by ManikandanV** [comment]
I did the same, but this is not working for me. Can you help me?

**Comment by justinjoseph89** [comment]
Hi Manikandan,
Please check you followed the below steps
STEP 1

create a table that u want to add the data,

CREATE TABLE logs (type STRING, time STRING, ext STRING, ip STRING, req STRING, res INT, bytes INT, phpmem INT, agent STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

STEP 2

Add data to the table(Here its a log file apache.log)

LOAD DATA INPATH '/user/apache/apache.log' OVERWRITE INTO TABLE logs;

STEP 3

Add Jar file into the class path (Note that Version 2.1.0.BUILD-SNAPSHOT.jar)

ADD JAR elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar;

STEP 4

Create a table eslogs which u want to use in the localhosts elasticsearch

CREATE EXTERNAL TABLE eslogs (time STRING, extension STRING, clientip STRING, request STRING, response INT, agent STRING) STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'test/test','es.mapping.names' = 'time:@timestamp', 'es.nodes' = 'IP_ON_WHICH_ELASTICSEARCH_IS_RUNNING:9200');

STEP 5

ADD the data into the eslogs from logs table

INSERT OVERWRITE TABLE eslogs SELECT s.time, s.ext, s.ip, s.req, s.res, s.agent FROM logs s;


Still not yet working please check your versions of jar file.

**Comment by ManikandanV** [comment]
Hi Justin, 
  Thanks for the steps. Actually I am new to Hadoop and Hive.

I am using below configuration. 

Hadoop version - 2.6.0
Hive version - 1.0
ElasticSearch - 1.2.2

I have added the jar elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar

Still Hive returning error. Then I have checked the application log, there I found the below error.

Log 1: 
[Fatal Error] job.xml:665:51: Character reference "&#0" is an invalid XML character.

Log 2: 
2015-03-27 12:41:51,060 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Created MRAppMaster for application appattempt_1427431806640_0012_000001
2015-03-27 12:41:51,474 FATAL [main] org.apache.hadoop.conf.Configuration: error parsing conf job.xml
org.xml.sax.SAXParseException; systemId: file:///tmp/hadoop-hduser/nm-local-dir/usercache/hduser/appcache/application_1427431806640_0012/container_1427431806640_0012_01_000001/job.xml; lineNumber: 665; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2352)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2421)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2374)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2281)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1108)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:51)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1421)
2015-03-27 12:41:51,477 FATAL [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
java.lang.RuntimeException: org.xml.sax.SAXParseException; systemId: file:///tmp/hadoop-hduser/nm-local-dir/usercache/hduser/appcache/application_1427431806640_0012/container_1427431806640_0012_01_000001/job.xml; lineNumber: 665; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2517)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2374)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2281)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1108)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:51)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1421)
Caused by: org.xml.sax.SAXParseException; systemId: file:///tmp/hadoop-hduser/nm-local-dir/usercache/hduser/appcache/application_1427431806640_0012/container_1427431806640_0012_01_000001/job.xml; lineNumber: 665; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2352)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2421)
	... 5 more
2015-03-27 12:41:51,479 INFO [main] org.apache.hadoop.util.ExitUtil: Exiting with status 1

**Comment by sandesh2014** [comment]
@ManikandanV  Did you get it work. As even im facing the same issue. If you got it working, please do share info with me

Team - Can any one provide info on how-to overcome this issue.

**Comment by ManikandanV** [comment]
Hi everyone,

The issue mentioned above is fixed for me. I have removed old es-hadoop jars from hadoop and hive classpath. Here is my configurations.

Hadoop - 2.6.0
Hive - 1.0
elasticsearch-hadoop-2.0.3.BUILD-20150327.030156-153.jar

Thanks @justinjoseph89

**Comment by wfowlks** [comment]
Thanks for this. It helped me fix my problem: 

Here are my versions:
Hortonworks Hadoop 2.4.0.2.1.5.0-695
Hive hive-hwi-0.13.0.2.1.5.0-695.jar
elasticsearch-hadoop-2.1.0.BUILD-20150402.023419-350

2nd Thanks @justinjoseph89
